### ISSUE TITLE
Alinhamento do design das tables

### ISSUE THREAD

**Issue by Ronkiro** [danilomacb/4noobs-web#1]
![image](https://user-images.githubusercontent.com/27526023/88824433-b8938380-d19c-11ea-810f-a8d343264586.png)

Acho interessante que as tables tenham espaçamentos/larguras semelhantes. Isto auxilia tanto na questão de UX quanto em UI.

Além disso, creio que também auxiliaria ao ícone do botão estar posicionado sempre de forma parecida.

**Comment by danilomacb** [comment]
![image](https://user-images.githubusercontent.com/39657417/89122860-5048e880-d4a1-11ea-8655-a7be3aac2c02.png)

Não sei se entendi direito, mas acho que você ta falando do alinhamento dos icones das setas nos links né? Bom esse print ai é do 4noobs no github, e o comportamento é o mesmo, o conteúdo fica todo a esquerda. E como a ideia da plataforma é exibir apenas o que ta nos reposiotórios, eu não sei se vai ser uma boa alterar esse comportamento.

**Comment by Ronkiro** [comment]
É exatamente esse comportamento. Não sei se seria possível sem quebrar algo, mas achei uma questão interessante de tentar (Ainda não tive tempo de dar uma olhada no código para poder ver se consigo fazer algo KKKK).

Acho que seria um bom agregante em questão de experiência de usuário, mas se for o caso de ficar muito complicado, acho que o esforço não vale a pena.

**Comment by danilomacb** [comment]
Na real ate da, mas todo o conteudo de todas as tabelas ficaria centralizado, nao sei se seria uma boa, dai eu acabei copiando o comportamento do github msm.
