### ISSUE TITLE
Adicionar um tamanho maximo na logo do projeto

### ISSUE THREAD

**Issue by JVictorV** [danilomacb/4noobs-web#3]
Em telas muito grandes a logo fica desproporcionalmente grande e dificulta a leitura, testei na resolucao 2560x1080

![Screenshot from 2020-08-12 12-19-04](https://user-images.githubusercontent.com/40485924/90033851-4cce1200-dc96-11ea-845b-11286188a2f4.png)

**Comment by danilomacb** [comment]
Corrigido no commit https://github.com/danilomacb/4noobs-web/commit/1dee1017748b745f785f3ed19d3fbe6900b836b8.
